import { Product } from "@prisma/client";

export const DemoData: Product[] = [
    {
        id: "1",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "2",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "3",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "4",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "5",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "6",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "7",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "8",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "9",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "10",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "11",
        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "12",

        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
    {
        id: "13",

        name: "Nike Air Max 270",
        fullDescription: "Men's Running Shoes with Air cushioning",
        sellingPrice: 150.00,
        discountPrice: 129.99,
        saleCount: 1200,
        stock: 250,
        imageUrl: "/placeholder.svg",
        brand: "Nike",
        categoryId: "cat-001",
        deliveryCharge: 100,
        dimensions: "100x100x100",
        isDeleted: false,
        isFeatured: true,
        metaDescription: "Men's Running Shoes with Air cushioning",
        metaTitle: "Nike Air Max 270",
        shortDescription: "Men's Running Shoes with Air cushioning",
        sku: "123456789",
        status: "ACTIVE",
        stockAlert: 10,
        trackInventory: true,
        weight: 100,
        videoUrl: "https://www.youtube.com/watch?v=123456789",
        cost: 1000,
        inStock: true,
        subCategoryId: "run-001",
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01")
    },
]
